# Generated by Django 2.0.3 on 2018-03-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmct', '0005_auto_20180328_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='size',
            field=models.FloatField(default=0),
        ),
    ]
